# Generated by Django 5.1 on 2024-08-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('caste', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('adharaNo', models.IntegerField()),
                ('rollno10th', models.IntegerField()),
                ('Marks10th', models.IntegerField()),
                ('rollno12th', models.IntegerField()),
                ('Marks12th', models.IntegerField()),
                ('gateScore', models.IntegerField()),
                ('gateRollNo', models.IntegerField()),
                ('gateRank', models.IntegerField()),
                ('graduationScore', models.IntegerField()),
                ('graduationYear', models.IntegerField()),
                ('graduationCourse', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
            ],
        ),
    ]
